language: android
jdk: oraclejdk8
dist: trusty
sudo: true

android:
  components:
    - platform-tools
    - tools
    # mPower
    - build-tools-26.0.2
    - android-26
    # CRF
    - build-tools-25.0.2
    - android-25

script:
    - ./gradlew build
